"""
QA Prompt Templates

Builds structured prompts for test report generation and feature testing.
"""

from typing import Optional


def build_test_report_prompt(
    app_name: str,
    app_description: Optional[str] = None,
) -> str:
    """
    Build a comprehensive QA test report prompt.

    Args:
        app_name: Name or package of the app to test
        app_description: Optional context about the app's purpose

    Returns:
        Formatted prompt string for run_task()
    """

    context_section = ""
    if app_description:
        context_section = f"""
**App Context:** {app_description}
Use this context to prioritize testing relevant features and workflows.
"""

    prompt = f"""**Role:** Senior Mobile QA Automation Engineer

**App Under Test:** {app_name}
{context_section}
**Objective:** Execute a comprehensive QA workflow on this Android application and generate a structured test report.

**CRITICAL RULES**

1. **Text Field Handling**
    **Before entering ANY text in ANY input field throughout testing:**
    - **ALWAYS clear the field first** — select all text and delete, or clear the field completely
    - **Verify the field is empty** before typing new content
    - **Do NOT assume fields are empty** — previous test data may persist

    This applies to: login fields, search fields, form inputs, dialogs with text fields, etc.

**Testing Protocol:**

**Phase 1: Launch & Initialization**
1. Launch the app from a cold state
2. Measure approximate time-to-interactive
3. Verify the main screen loads without errors
4. Check for any startup dialogs, permissions, or onboarding flows

**Phase 2: Core Navigation**
1. Identify and navigate to all main screens/tabs
2. Test the back button behavior from each screen
3. Verify navigation transitions are smooth
4. Check that the home/main screen is always accessible

**Phase 3: User Interactions**
1. Test all visible buttons and tappable elements
2. Test any input fields with valid data
3. Test scrolling in lists or content areas
4. Test any pull-to-refresh functionality if present
5. Test any floating action buttons or menus

**Phase 4: Edge Cases & Error Handling**
1. Test input fields with empty/blank input
2. Test rapid consecutive taps
3. Test navigation during loading states
4. Look for any UI glitches, overlapping text, or layout issues

**Phase 5: Stability Assessment**
1. Monitor for any crashes or ANRs (App Not Responding)
2. Note any freezes or unresponsive moments
3. Check memory behavior (if app becomes sluggish)
---

**REQUIRED OUTPUT FORMAT:**

You MUST compile your findings into the following Markdown report structure:

# 📱 {app_name} - QA Test Report

## 1. Executive Summary
| Metric | Value |
|--------|-------|
| **App Name** | {app_name} |
| **Test Date** | [Current Date] |
| **Overall Stability** | [Stable / Unstable / Crashed] |
| **Tests Executed** | [Number] |
| **Pass Rate** | [X/Y] ([Percentage]%) |

## 2. Test Results

| TC-ID | Feature Area | Test Action | Expected Result | Actual Result | Status |
|-------|--------------|-------------|-----------------|---------------|--------|
| TC-001 | Launch | Cold start app | App loads < 5s | [Observation] | PASS/FAIL |
| TC-002 | Navigation | Navigate to main screens | All screens accessible | [Observation] | PASS/FAIL |
| TC-003 | Interaction | Tap primary buttons | Buttons respond correctly | [Observation] | PASS/FAIL |
| TC-004 | Input | Enter text in fields | Text accepted | [Observation] | PASS/FAIL |
| TC-005 | Scrolling | Scroll content areas | Smooth scrolling | [Observation] | PASS/FAIL |
| TC-006 | Back Navigation | Press back button | Returns to previous screen | [Observation] | PASS/FAIL |
| [Continue for all tests...] |

## 3. Defects Found

If no defects found, state: "✅ No critical defects found during testing."

For each defect:
### 🐛 BUG-[ID]: [Brief Title]
- **Severity:** [Critical / High / Medium / Low]
- **Steps to Reproduce:**
  1. [Step 1]
  2. [Step 2]
  3. [Error occurs]
- **Expected:** [What should happen]
- **Actual:** [What actually happened]

## 4. UX & Performance Observations
- **Load Time:** [Comments on app startup speed]
- **Responsiveness:** [Comments on touch response and animations]
- **Layout:** [Comments on UI layout, text readability, element spacing]
- **Stability:** [Comments on crashes, freezes, or memory issues]

## 5. Recommendations
- [Recommendation 1]
- [Recommendation 2]
- [...]

---
*Report generated by BlueStacks MCP QA Agent*
"""

    return prompt


def build_feature_test_prompt(
    app_name: str,
    feature_name: str,
    feature_description: str,
) -> str:
    """
    Build a focused prompt for testing a specific feature.

    Args:
        app_name: Name or package of the app
        feature_name: Name of the feature to test (e.g., "Login Flow")
        feature_description: Detailed description of the feature and how to test it

    Returns:
        Formatted prompt string for run_task()
    """

    prompt = f"""**Role:** Senior Mobile QA Automation Engineer

**App Under Test:** {app_name}
**Feature Under Test:** {feature_name}

**Feature Description:**
{feature_description}

**Objective:** Thoroughly test this specific feature and generate a focused test report.

**CRITICAL RULES**

1. **Text Field Handling**
    **Before entering ANY text in ANY input field throughout testing:**
    - **ALWAYS clear the field first** — select all text and delete, or clear the field completely
    - **Verify the field is empty** before typing new content
    - **Do NOT assume fields are empty** — previous test data may persist

    This applies to: login fields, search fields, form inputs, dialogs with text fields, etc.

**Testing Approach:**

1. **Navigate to Feature:**
   - Launch the app if not already running
   - Navigate to the screen/area where this feature exists

2. **Happy Path Testing:**
   - Test the feature with valid/expected inputs
   - Verify the feature works as described
   - Confirm success states and feedback

3. **Edge Case Testing:**
   - Test with empty/blank inputs where applicable
   - Test with boundary values
   - Test rapid/repeated interactions
   - Test interruptions (back button, home, etc.)

4. **Error Handling:**
   - Test with invalid inputs if applicable
   - Verify error messages are clear and helpful
   - Ensure the app doesn't crash on bad input

5. **State Verification:**
   - Verify data persistence if applicable
   - Check state after background/foreground cycling
   - Verify integration with other features

---

**REQUIRED OUTPUT FORMAT:**

# 🔍 Feature Test Report: {feature_name}

## Summary
| Metric | Value |
|--------|-------|
| **App** | {app_name} |
| **Feature** | {feature_name} |
| **Test Date** | [Current Date] |
| **Overall Status** | [PASS / FAIL / PARTIAL] |
| **Tests Executed** | [Number] |
| **Pass Rate** | [X/Y] ([Percentage]%) |

## Test Cases

| TC-ID | Test Scenario | Input/Action | Expected | Actual | Status |
|-------|---------------|--------------|----------|--------|--------|
| FT-001 | [Scenario] | [Action] | [Expected] | [Actual] | PASS/FAIL |
| FT-002 | [Scenario] | [Action] | [Expected] | [Actual] | PASS/FAIL |
| [Continue...] |

## Defects Found

If no defects: "✅ No defects found in {feature_name}."

For each defect:
### 🐛 [ID]: [Title]
- **Severity:** [Critical/High/Medium/Low]  
- **Steps:** [1, 2, 3...]
- **Expected vs Actual:** [Comparison]

## Observations
- [Observation about feature behavior]
- [Performance notes]
- [UX feedback]

## Recommendation
[Pass to production / Needs fixes / Block release]

---
*Feature test by BlueStacks MCP QA Agent*
"""

    return prompt
